### ISSUE TITLE
Sharing configuration not working

### ISSUE THREAD

**Issue by olaquetal** [openwebnet/openwebnet-site#3]
Hi,
thank you very much for your very nice application.
I'm using it on android and I would like to share the configuration with my family. How can I do that ?
I've created a profile with my google account but when I click on "profile" I have only an error message saying "nothing found".
Is it maybe because I have a double identification on this google account?
Thanks

**Comment by niqdev** [comment]
Hi, I test it now and it should work. Would you mind opening an issue [here](https://github.com/openwebnet/openwebnet-android/issues) attaching some screenshots of the error and a more detailed explanation of the steps you did?
Thanks
